use crate::kaomoji::KaomojiEntry;

pub fn builtin_kaomoji() -> Vec<KaomojiEntry> {
    vec![
        // Happy
        entry("(◕‿◕)", "happy", "happy"),
        entry("(｡◕‿◕)", "happy", "happy"),
        entry("(≧◡≦)", "happy", "happy"),
        entry("(^_^)", "happy face", "happy"),
        entry("(ﾉ◕ヮ◕)ﾉ*:・゚✧", "sparkly happy", "happy"),
        entry("(´∀｀)", "happy", "happy"),
        entry("(⌒‿⌒)", "happy", "happy"),
        entry("(◠‿◠)", "happy", "happy"),
        entry("(✿◠‿◠)", "happy with flower", "happy"),
        entry("(◠‿・)—☆", "winking happy", "happy"),
        entry("(｡◕‿◕｡)", "happy", "happy"),
        entry("(^‿^)", "smiling", "happy"),
        entry("(*^▽^*)", "cheerful", "happy"),
        entry("(⌒▽⌒)☆", "happy star", "happy"),
        entry("(ﾉ´ヮ`)ﾉ*: ・゚✧", "excited", "happy"),
        entry("٩(◕‿◕)۶", "celebrating", "happy"),
        entry("(imeInterval)", "happy", "happy"),
        entry("(ᗒᗨᗕ)", "happy", "happy"),
        entry("(★‿★)", "star eyes", "happy"),
        entry("(◕ᴗ◕✿)", "happy blooming", "happy"),
        entry("(≧ω≦)", "gleeful", "happy"),
        entry("(o^▽^o)", "cheerful", "happy"),
        entry("(⌒ω⌒)", "cute happy", "happy"),
        entry("(●´ω｀●)", "happy", "happy"),
        entry("(❁´◡`❁)", "happy", "happy"),
        entry("(◠ω◠)", "happy", "happy"),
        entry("(✿✿✿)", "flower happy", "happy"),
        entry("(＾▽＾)", "grinning", "happy"),

        // Sad
        entry("(╥_╥)", "crying", "sad"),
        entry("(T_T)", "crying", "sad"),
        entry("(;_;)", "crying", "sad"),
        entry("(ಥ_ಥ)", "crying", "sad"),
        entry("(ಥ﹏ಥ)", "sobbing", "sad"),
        entry("(;﹏;)", "sad tears", "sad"),
        entry("(｡•́︿•̀｡)", "sad", "sad"),
        entry("(っ˘̩╭╮˘̩)っ", "hugging sad", "sad"),
        entry("(ಥ◡ಥ)", "sad", "sad"),
        entry("(´;ω;`)", "crying", "sad"),
        entry("(｡ŏ﹏ŏ)", "distressed", "sad"),
        entry("(ノД`)・゜・。", "sad", "sad"),
        entry("(；ω；)", "teary", "sad"),
        entry("(-̩̩-̩̩͍_-̩̩-̩̩͍)", "very sad", "sad"),
        entry("(´・ω・`)", "sad", "sad"),
        entry("(｡╯︵╰｡)", "sad", "sad"),
        entry("(┯﹏┯)", "crying sad", "sad"),
        entry("(╥﹏╥)", "wailing", "sad"),
        entry("(இ﹏இ)", "crying", "sad"),

        // Angry
        entry("(╬Ò﹏Ó)", "furious", "angry"),
        entry("(ノಠ益ಠ)ノ", "table flip angry", "angry"),
        entry("(≖_≖)", "unamused", "angry"),
        entry("(눈_눈)", "glaring", "angry"),
        entry("(¬_¬)", "side eye", "angry"),
        entry("(≖▄≖)", "angry", "angry"),
        entry("(ᗒᗣᗕ)՞", "angry", "angry"),
        entry("(＃`Д´)", "yelling", "angry"),
        entry("(눈_ʖ눈)", "angry stare", "angry"),
        entry("(ᗒᗣᗕ)՞", "furious", "angry"),
        entry("(╬▔皿▔)╯", "very angry", "angry"),
        entry("(ᗒᗩᗕ)", "angry", "angry"),
        entry("щ(ಠ益ಠщ)", "angry", "angry"),
        entry("(ò_ó)", "angry", "angry"),
        entry("(ᗒᗣᗕ)՞", "mad", "angry"),
        entry("(*≖ ヮ ≖*)", "angry pout", "angry"),
        entry("(ᗒᗣᗕ)՞", "irate", "angry"),
        entry("(≖_≖✿)", "passive aggressive", "angry"),

        // Confused
        entry("(⊙_☉)", "confused", "confused"),
        entry("(°□°)", "shocked", "confused"),
        entry("(ー_ー)", "unsure", "confused"),
        entry("(・・?)", "confused", "confused"),
        entry("(⊙_◎)", "bewildered", "confused"),
        entry("(☉_☉)", "surprised", "confused"),
        entry("(ˊ̥ˋ̥ㅂˋ̥)", "confused", "confused"),
        entry("(・–・;)ゞ", "confused bow", "confused"),
        entry("(⊙ω⊙)", "surprised", "confused"),
        entry("(・・？)", "huh?", "confused"),
        entry("（・∀・）", "blank stare", "confused"),
        entry("(¬_¬ )", "skeptical", "confused"),
        entry("(・・;)", "sweating confused", "confused"),
        entry("(°ー°〃)", "dizzy confused", "confused"),
        entry("(ーー;)", "uncertain", "confused"),
        entry("(・∀・;)", "nervous laugh", "confused"),

        // Love
        entry("(♥ω♥)", "love", "love"),
        entry("(◍•ᴗ•◍)❤", "love", "love"),
        entry("(◕‿◕✿)", "love bloom", "love"),
        entry("(っ˘ω˘ς)", "loving", "love"),
        entry("(づ♡ど)", "offering love", "love"),
        entry("(´,,•ω•,,)♡", "blushing love", "love"),
        entry("(◍•ᴗ•◍)❤", "heart eyes", "love"),
        entry("(✿♡‿♡)", "love", "love"),
        entry("(❤ω❤)", "heart love", "love"),
        entry("(っ˘з(˘⌣˘ )", "kiss", "love"),
        entry("(づ￣³￣)づ", "hugging kiss", "love"),
        entry("(っ˘з(˘⌣˘ )", "kiss kiss", "love"),
        entry("(´∩｡• ᵕ •｡∩`)", "loving", "love"),
        entry("(◍•ᴗ•◍)❤", "adoring", "love"),
        entry("(っ˘ω˘ς)", "sweet love", "love"),
        entry("(♡μ_μ)", "love struck", "love"),
        entry("(´,,•ω•,,)♡", "shy love", "love"),

        // Animals
        entry("(ʕ•ᴥ•ʔ)", "bear", "animals"),
        entry("(=^・ω・^=)", "cat", "animals"),
        entry("(\\__/)", "bunny", "animals"),
        entry("(・(ｴ)・)", "dog", "animals"),
        entry("(^._.^)ﾉ", "cat wave", "animals"),
        entry("(=①ω①=)", "cat face", "animals"),
        entry("(ʕ◉ᴥ◉ʔ)", "bear happy", "animals"),
        entry("(•ᴥ•)", "bear", "animals"),
        entry("ʕっ•ᴥ•ʔっ", "bear hug", "animals"),
        entry("(=ↀωↀ=)", "cat", "animals"),
        entry("(っFTωTF)っ", "cat hug", "animals"),
        entry("(≡•ω•≡)", "cat", "animals"),
        entry("(・(unks)・)", "fish", "animals"),
        entry("(° Tok°)", "fish", "animals"),
        entry("(V●ᴥ●V)", "dog", "animals"),
        entry("(╥ᆺ╥)", "sad cat", "animals"),
        entry("(=^‥^=)", "cat", "animals"),
        entry("₍˄·͈༝·͈˄₎◞", "cat", "animals"),

        // People
        entry("(づ￣³￣)づ", "hug", "people"),
        entry("(｡･ω･)ﾉﾞ", "wave hello", "people"),
        entry("٩(˘◡˘)۶", "cheer", "people"),
        entry("(づ｡◕‿‿◕｡)づ", "hug", "people"),
        entry("(｡◕‿◕)づ", "hand out", "people"),
        entry("(ノ◕ヮ◕)ノ*:・゚✧", "throw sparkles", "people"),
        entry("ヾ(⌐■_■)ノ", "sunglasses", "people"),
        entry("(•̀ᴗ•́)و", "fighting", "people"),
        entry("(⊃｡•́‿•̀｡)⊃", "hug", "people"),
        entry("(づ◡┳━__━┳◡)づ", "big hug", "people"),
        entry("(⌐■_■)", "cool", "people"),
        entry("( •_•)>⌐■-■", "putting on shades", "people"),
        entry("(⌐■̀_■́)", "cool deal", "people"),
        entry("(ᕗ ͠° ਊ ͠° )ᕗ", "flexing", "people"),
        entry("(•̀ᴗ•́)و ̑̑", "determined", "people"),
        entry("(づ-)͟͟͞͞ oli oli ol free", "free", "people"),
        entry("(¬‿¬)", "sly", "people"),
        entry("(ᗒᗣᗕ)՞", "excited person", "people"),

        // Hands
        entry("ヽ(>∀<☆)ノ", "excited hands", "hands"),
        entry("╰(*°▽°*)╯", "happy hands", "hands"),
        entry("ヾ(＠⌐■_■)ノ", "jazz hands", "hands"),
        entry("ヽ(´ー｀)ノ", "shrug hands", "hands"),
        entry("(ﾉ◕ヮ◕)ﾉ*:・゚✧", "sparkle hands", "hands"),
        entry("♪└(amoeba)┘", "dance hands", "hands"),
        entry("ヾ(⌐■_■)ノ♪", "music hands", "hands"),
        entry("ヽ(o＾▽＾o)ノ", "cheer hands", "hands"),
        entry("♪(´ε` )", "singing", "hands"),
        entry("ヾ(⌐■_■)ノ", "cool hands", "hands"),
        entry("ヽ(>∀<☆)ノ", "star hands", "hands"),
        entry("(ﾉ◕ヮ◕)ﾉ*:・゚✧", "magic hands", "hands"),

        // Tables
        entry("(╯°□°)╯︵ ┻━┻", "table flip", "tables"),
        entry("┬─┬ノ( º _ ºノ)", "put table back", "tables"),
        entry("(╯°□°)╯︵ ┻━┻", "table flip angry", "tables"),
        entry("┬─┬ノ(ò_óノ)", "put table back angry", "tables"),
        entry("(┛✧Д✧))┛彡┻━┻", "throw table", "tables"),
        entry("(ﾉꐦ ⊱ ꐦ)ﾉ彡┻━┻", "flip table", "tables"),
        entry("┬─┬﻿ ノ( º _ º ノ)", "calm table", "tables"),
        entry("(┛ಸ_ಸ)┛彡┻━┻", "flip table hard", "tables"),
        entry("┬─┬ノ(ಠ_ಠノ)", "restore table", "tables"),
        entry("(┛◉Д◉)┛彡┻┻┻", "double table flip", "tables"),
        entry("┬┴┬┴┤(･_├┬┴┬┴", "table hiding", "tables"),
        entry("(┛olla_olla)┛彡┻━┻", "flip", "tables"),
        entry("(┛✧Д✧))┛彡┻━┻", "fury flip", "tables"),
        entry("┬─┬﻿ (ಠ_ಠ﻿)", "no table flip", "tables"),
        entry("┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻", "double flip", "tables"),
        entry("(┛ಸ_ಸ)┛彡┻━┻┻", "extra flip", "tables"),

        // Misc
        entry("¯\\_(ツ)_/¯", "shrug", "misc"),
        entry("( ͡° ͜ʖ ͡°)", "lenny face", "misc"),
        entry("ಠ_ಠ", "disapproving", "misc"),
        entry("ಠ益ಠ", "angry look", "misc"),
        entry("┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴", "lenny hiding", "misc"),
        entry("( ͡° ͜ʖ ͡°)", "lenny", "misc"),
        entry("┬┴┬┴┤├┬┴┬┴", "table fence", "misc"),
        entry("( ͡~ ͜ʖ ͡°)", "lenny smirk", "misc"),
        entry("ಠ~ಠ", "disappointed", "misc"),
        entry("( ͡╥ ͜ʖ ͡╥)", "lenny cry", "misc"),
        entry("( •_•)>■□■< (•_• )", "fight", "misc"),
        entry("( ˘▽˘)っ♨", "offer food", "misc"),
        entry("(づ￣ ³￣)づ", "want kiss", "misc"),
        entry("┬┴┬┴┤(･_├┬┴┬┴", "hiding", "misc"),
        entry("(⌐□_□)", "deal with it", "misc"),
        entry("( •_•):█▓▒░", "typing", "misc"),
        entry("( ͡° ͜V ͡°)", "lenny v", "misc"),
        entry("♪～(´ε` )", "humming", "misc"),
        entry("( ͡^ ͜ʖ ͡^ )", "lenny happy", "misc"),
        entry("(⌐ ͡° ͜ʖ ͡°)", "lenny glasses", "misc"),
        entry("(⌐■-■)", "cool", "misc"),
        entry("( •_•)>⌐■-■", "deal", "misc"),
        entry("┬┴┬┴┤ ͡° ͜ʖ├┬┴┬┴", "lenny peeking", "misc"),
        entry("┻━┻ ︵ ¯\\(ツ)/¯ ︵ ┻━┻", "confused flip", "misc"),
        entry("( ͡°∪ ͡°)", "lenny happy", "misc"),
        entry("┌ಠ_ಠ)┌∩┐", "middle fingers", "misc"),
        entry("( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°) ͜ʖ ͡°) ͡°)", "lenny inception", "misc"),
        entry("(⌐⌐■_■)", "cool sunglasses", "misc"),
        entry("(∩｀-´)⊃━☆ﾟ.*･｡ﾟ", "magic", "misc"),
        entry("(⌐■-■)ノ♫", "cool music", "misc"),
        entry("( ͡° ͡°)", "suspicious", "misc"),
        entry("(ᵔᴥᵔ)", "happy eyes", "misc"),
        entry("(ง •̀_•́)ง", "fight me", "misc"),
        entry("(•_•)", "thinking", "misc"),
        entry("( •_•)>⌐■-■", "putting on glasses", "misc"),
        entry("(⌐■_■)", "done", "misc"),
        entry("(◕‿◕)", "content", "misc"),
        entry("(ᵔᴥᵔ)", "cute face", "misc"),
        entry("( ͡° ͜ʖ ͡°)", "lenny classic", "misc"),
        entry("(▀̿Ĺ̯▀̿ ̿)", "angry table", "misc"),
        entry("┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴", "lenny hiding table", "misc"),
        entry("ᕦ(ò_óˇ)ᕤ", "flex", "misc"),
        entry("(づ｡◕‿‿◕｡)づ", "reach hug", "misc"),
        entry("(•_•)⚡(•_•)", "electric", "misc"),
        entry("ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ", "triple bear", "misc"),
        entry("(̿▀͜ ̿ ‿ ̿ ✿ )", "angry flower", "misc"),
        entry("(╥﹏╥)", "crying", "misc"),
        entry("( ˘ω˘ )", "sleepy", "misc"),
        entry("( _ )", "person", "misc"),
        entry("(ง'̀-'́)ง", "fight", "misc"),
        entry("(◕‿◕✿)", "happy flower", "misc"),
        entry("(ᗒᗣᗕ)՞", "surprised", "misc"),
        entry("( ͡° ͜V ͡°)", "lenny v2", "misc"),
        entry("(⌐■-■)ノ", "cool wave", "misc"),
        entry("(•̀ᴗ•́)و", "power", "misc"),
        entry("(ᵔᴥᵔ)", "bear face", "misc"),
        entry("ᕦ(ò_óˇ)ᕤ", "muscle", "misc"),
        entry("(⌐■_■)♪", "cool music", "misc"),
        entry("(⌐■-■)♫", "sunglasses music", "misc"),
        entry("(⌐■_■)ノ♫♪", "party cool", "misc"),
    ]
}

fn entry(chars: &str, description: &str, category: &str) -> KaomojiEntry {
    KaomojiEntry {
        chars: chars.to_string(),
        description: description.to_string(),
        categories: category.split(',').map(|s| s.trim().to_string()).collect(),
    }
}
